name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run oa:init
      - run: npm run oa:gen
      - run: npm run biome:chk
      - run: npm run tsc:bld
      - id: pack-file-name
        run: echo "PACK_FILE_NAME=$(npm pack --loglevel=silent)" >> "$GITHUB_ENV"
      - run: npm publish --provenance --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.PACK_FILE_NAME }}
